spring:
  mail:
   host: smtp.qq.com
   username: 1013427541@qq.com
   password: iisbykzgjfikbdhg
   properties:
    mail:
      smtp:
       auth: true # 这样才能通过验证
       starttls:
        enable: true
        required: true