server:
  port: 8181
spring:
  redis:
    database: 0
    host: 192.168.1.114
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-wait: 8
      max-active: -1
#    password:
    timeout: 0
  datasource:
    url: jdbc:mysql://localhost:3306/live?characterEncoding=utf8&amp;useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    mode: HTML5


#mybatis ≈‰÷√
mybatis:
  type-aliases-package: com.chen.logic.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  configLocation: classpath:mybatis/mybatis-config.xml



