server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&amp;useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.1.114 #地址
    pool: 6379 #端口号
      max-idle: 8 #连接池中的最大空闲连接
      max-wait: 8 #连接池最大连接数（使用负值表示没有限制）
      min-idle: 0 #连接池中的最小空闲连接
      max-active: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
    database: 0 #索引（默认为0）
    password:
    timeout: 0 #连接超时时间（毫秒）
  thymeleaf:
    mode: LEGACYHTML5



