server:
  port: 8087
  context-path: /
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#关闭SpringBoot的缓存
  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: com.chen.entity
  mapper-locations: classpath:mapper/*.xml
