## Dubbo 服务提供者配置
dubbo:
  application:
    #应用名称
    name: provider
  registry:
    #注册中心地址
    address: zookeeper://192.168.1.113:2180
  protocol:
    #协议名称
    name: dubbo
    #协议端口
    port: -1
  scan:
  # 服务类包目录
    dubbo: com.chen.dubbo.impl

server:
  port: 9001

